### PR TITLE
Added delete and search.

### PR DESCRIPTION
**Pull request by benbenwilde**
Hey I added a simple delete method so that you can delete by just passing in the id or ids.

But I haven't actually been able to test it yet, so if you can maybe look at it quick that would be great, I'll let you know if I get around to testing it.

Thanks.

### CODE REVIEW

**Comment by clamidity** [comment]
I'll work on testing it. Looks great so far.

**Comment by benbenwilde** [comment]
thanks!

**Comment by benbenwilde** [comment]
Tested and the delete works great.

**Comment by benbenwilde** [comment]
Ok I just threw search in here cuz i needed it on my end - tested that as well and seems great.
Also added some more documentation and updated the ISalesforceClient interface accordingly.

This PR should be ready to go.

**Comment by benbenwilde** [comment]
Also updated the readme - we'll have to update some of the wikis once this is pulled in to to reflect the changes. Might not hurt to go to version 0.3 considering the amount of recent feature adds? :)

**Comment by clamidity** [comment]
Sorry, I have been out of town. I'll take a look.

**Comment by benbenwilde** [comment]
Thanks, I'm sure you will like it.

**Comment by benbenwilde** [comment]
Hey, do you think we would be able to move this through soon? I'm happy to make adjustments if you have thoughts about it. Would just be nice to have it up in nuget :)
Thanks again!

**Comment by clamidity** [comment]
Quick question on this one. I noticed that the delete template now only has a reference to the ids? This might break functionality with the other delete methods (allowing you to delete by passing the object). What are your thoughts on this?

**Comment by benbenwilde** [comment]
You can still delete both ways because I left the original delete methods on the client. The delete template used to pull the ids off the objects for deleting, and now instead, the ids are pulled off the objects when the template is created (as opposed to when it is read). So previous functionality should still be working the same.

**Comment by benbenwilde** [comment]
Any other thoughts?

**Comment by clamidity** [comment]
This looks good, I'll get this in today.

**Comment by clamidity** [comment]
pushed to nuget

**Comment by benbenwilde** [comment]
awesome! thanks man

**Pull request merged**
