### PR TITLE
Added Test Project and minor update to SOQLVisitor

### PR DESCRIPTION
**Pull request by benbenwilde**
I added a test project to aid in testing this project to help ensure everything works perfectly. It references NuGet packages for NUnit and Shouldly. Let me know if it's not quite what your looking for.

Also, in order to test SOQLVisitor, I unfortunately had to change the access on that class and one of its methods. Any thoughts are welcome.

### CODE REVIEW

**Comment by benbenwilde** [comment]
related to #17

**Comment by clamidity** [comment]
This is great. Merging now.

**Comment by clamidity** [comment]
This fix has now been published to nuget.

**Comment by benbenwilde** [comment]
Very cool! I'm already using it. Thanks for all your work on this library, it's really coming in handy right now!

**Pull request merged**
