### PR TITLE
Retrieve and Batch Size

### PR DESCRIPTION
**Pull request by benbenwilde**
This pull request adds capability for the 'retrieve' SOAP API, to allow for retrieving of an object based on id, including automating filling of an SObject.

Included also is the ability to specify the batch size for queries at the config or session level. This is important if you want to configure your pagesize on queries.

Also includes a few minor improvements and minor refactoring of SoapCommands.cs.

Please let me know if you would like me to do anything differently!
Ben

### CODE REVIEW

**Comment by benbenwilde** [comment]
If this is good to go it would be fantastic to have this up in nuget really soon as possible, thanks for all your work on this library!

**Comment by clamidity** [comment]
This is great. I'll get it pushed,

**Comment by clamidity** [comment]
Pushed 0.2.3.5

**Comment by benbenwilde** [comment]
fantastic!

**Pull request merged**
